version: "3.8"
services:

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=app,keycloak
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

  pgadmin:
    user: 5050:5050
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGDATA: /var/lib/pgadmin/data
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"

  app:
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - pgadmin

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "28080:8080"
    depends_on:
      - db

volumes:
  db:
    driver: local