version: "3.8"
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    user: 5050:5050
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGDATA: /var/lib/pgadmin/data
    volumes:
      - ./data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
  app:
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - pgadmin
volumes:
  db:
    driver: local